---
title: "1995-03 Dashboard"
subtitle: "Monthly Dashboard for Beer sold at Dominick's: March 1995"
draft: true
format:
  html:
    toc: true
    toc-expand: 2

categories:
  - Dominicks
  - Beer
  - GEKS
---

# Overview

```{r}
#| echo: false
#| warning: false

period <- "1995-03"
category_name <- "ber"

source("R/diagnostics.R")

bar_df <- overview_table(period, category_name)

datatable(bar_df, options = list(
  dom = 't' # i.e. Table only
))
```

# Diagnostics

## Analytical (output) diagnostics



## Input diagnostics


## Monitoring / data validation

### Weeks in scope

The following weeks' data was used a input for the last month.

```{r}
#| echo: false
#| warning: false

results <- monitoring_stats(period, category_name)

results$period_data <- results$period_data[, c(
  "WEEK", 
  "week_start", 
  "week_end", 
  "distinct_upcs",
  "distinct_nitems",
  "total_sales",
  "number_of_rows",
  "distinct_stores",
  "distinct_com_codes",
  "distinct_zones",
  "ref_period")]

datatable(
      results$period_data,
      extensions = 'Buttons', # For the colvis button
      options = list(
        # 'B' adds buttons, 't' is the table
        dom = 'Bt', 
        buttons = c('colvis'),
        columnDefs = list(
          list(
            visible = FALSE,      # Hide columns by default
            targets = c(4, 8, 9, 10, 11)     # Hide a few to simplify UI
          )
        ),
        # Force table to occupy full container width
        autoWidth = TRUE,
        width = '100%'
      )
    )
```

### Week by week breakdown
```{r}
#| echo: false
#| warning: false

library(plotly)
library(htmltools)

widgets <- plot_weekly_stats(results$period_data, results$weekly_stats)
widgets
```